Style/StringLiterals:
  EnforcedStyle: "double_quotes"
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/AsciiComments:
  Enabled: false
